name: Workflow security

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflow-security:
    uses: ./.github/workflows/reusable-workflow-security.yml
    with:
      python_version: "3.11"
      analysis_endpoint: tools/ci/workflow-security
