name: Workflow security

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflow-security:
    uses: TeaShaman-cyber/marcopolo-cookbook/.github/workflows/reusable-workflow-security.yml@fe6a6b1f5e39cc5e9dfe6b580fd92f765e4af265
    with:
      python_version: "3.11"
      analysis_endpoint: tools/ci/workflow-security
